#!/bin/sh

# BE CAREFUL WITH SPACE, MAY FAIL TO WORK
regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
	echo your email $email satisfyies Git policy
	exit 0
else
	echo "your email $email does not satisfy Git policy"
	exit 1

fi		